SportShopProject/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderedProducts = new HashSet<OrderedProduct>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Article { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedProduct> OrderedProducts { get; set; }
        public virtual Category Category { get; set; }
    }
}

SportShopProject/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportShopProject.Models;
using SportShopProject.WebUI.Models;

namespace SportShopProject.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Menu(string selectedCategory = "")
        {
            List<string> categories;
            using(SportShopDBEntity entity = new SportShopDBEntity())
            {
                categories = entity.Categories.Select(c => c.Title).ToList();
            }
            categories.Insert(0, "Все продукты");
            ViewBag.SelectedCategory = selectedCategory.Replace('_',' ');
            return PartialView(categories);
        }
        public PartialViewResult PagesLinks(int page,int pageCount,string category)
        {
            int min, max;

            if (pageCount < 5)
            {
                min = 1;
                max = pageCount;
            }
            else
            {
                min = page - 2;
                max = page + 2;
                if (min < 1)
                {
                    max += -min + 1;
                    min = 1;
                }
                max = Math.Min(pageCount, max);
            }
            return PartialView(new PagesLinksViewModel(min, max,page,pageCount,category.Replace(' ','_')));
        }
    }
}

SportShopProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportShopProject.Models;
using SportShopProject.WebUI.Models;

namespace SportShopProject.Controllers
{
    public class ProductController: Controller
    {
        public const int productsPerPage = 8;
        public ActionResult Index()
        {
            return ProductList();
        }
        public ActionResult ProductList(string category = "Все продукты", int page = 1)
        {
            //Session["LastCatalogPage"] = Url.Action("ProductList", "Product", new { category = category, page = page });
            Session["LastCatalogPage"] = Request.RawUrl;
            List<Product> products;
            int productsCount;
            using (SportShopDBEntity entity = new SportShopDBEntity())
            {
                if (entity.Categories.Where(c => c.Title == category).Count() == 0)
                {
                    products = entity.Products.OrderBy(p => p.Id).Skip((page - 1) * productsPerPage).Take(productsPerPage).ToList();
                    productsCount = entity.Products.Count();
                }
                else
                {
                    products = entity.Products.Include("Category").Where(p => p.Category.Title == category).OrderBy(p => p.Id).Skip((page - 1) * productsPerPage).Take(productsPerPage).ToList();
                    productsCount = entity.Products.Include("Category").Where(p => p.Category.Title == category).Count();
                }
            }
            PageInfo pageInfo = new PageInfo(page, (int)Math.Ceiling(productsCount / (double)productsPerPage), category);

            return View("ProductList", new CategoryViewModel() { Products = products, pageInfo = pageInfo });
        }
        public ActionResult ProductView(string article)
        {
            Product product;
            string productCategory;
            using (SportShopDBEntity entity = new SportShopDBEntity())
            {
                product = entity.Products.FirstOrDefault(p => p.Article == article);
                productCategory = product.Category.Title;
            }
            CategoryViewModel viewModel = new CategoryViewModel() { Products = new List<Product>() { product } };
            return View(viewModel);
        }
    }
}

SportShopProject/Views/Product/ProductList.cshtml
@model CategoryViewModel

@{
    ViewBag.Title = "Каталог";
    ViewData["Category"] = Model.pageInfo.category;
    Layout = "~/Views/Shared/_CatalogLayout.cshtml";
}


<div class="container_products">
    @{
        foreach (var p in Model.Products)
        {
            <div class="product">   
                <a href="@Url.Action("ProductView","Product",new { article=p.Article })">
                    <div class="imageFrame">
                        <img src="@Url.Content("~/Images/Products/" + p.Article + "_Main.jpg")" />
                    </div>
                </a>
                <a href="@Url.Action("ProductView","Product",new { article=p.Article })">
                    <h2>@(Html.ProductType(p) + p.Title)</h2>
                </a>
                <p class="price">@p.Price руб.</p>
            </div>
        }
    }
</div>
@Html.Action("PagesLinks", "Nav", new { page = Model.pageInfo.page, pageCount = Model.pageInfo.pagesCount, category = Model.pageInfo.category })

SportShopProject/Views/Product/ProductProperties.cshtml
@model SportShopProject.Models.Product
<ul>
    <li>
        <span class="leftColumn">Производитель</span>
        <span class="rightColumn">@Model.Vendor</span>
    </li>
    <li>
        <span class="leftColumn">Артикул</span>
        <span class="rightColumn">@Model.Article</span>
    </li>
</ul>

SportShopProject/Views/Product/ProductView.cshtml
@model CategoryViewModel

@{
    SportShopProject.Models.Product product = Model.Products.FirstOrDefault();
    ViewBag.Title = Html.ProductType(product) + product.Title;
    Layout = "~/Views/Shared/_CatalogLayout.cshtml";
}

<div class="productView">
    <div class="horizontal imageBorder">
        <img src="@Url.Content("~/Images/Products/" + product.Article + "_Main.jpg")" />
    </div>
    <div class="horizontal addToCartView">
        <p class="price">@product.Price руб.</p>
        @using (Html.BeginForm("AddToCart", "Cart", new { article = product.Article, returnUrl = Request.Url.PathAndQuery }, FormMethod.Post))
        {
            <input class="btn btn-default" type="submit" value="Добавить в корзину" />
        }
    </div>
    <br />
    <div class="descriptionView horizontal fullWidth">
        <div tabindex="10" class="testClass">
            @product.Description
        </div>
    </div>
    <br />
    <div class="properyView horizontal fullWidth">
        <h3>Характеристики</h3>
        @Html.GetProperties(product)
    </div>
</div>